### ISSUE TITLE
Camera up vector

### ISSUE THREAD

**Issue by bugdanov** [potree/potree#300]
Hi !

Is there a way to set the camera "up" vector with 1.5RC ?
For the camera rotation Potree is now using pitch and yaw angles and assume the up vector is fixed.

I had no success yet playing with "roll" but I dont like using trigonometry for rotations.

I believe linear algebra is the way to go, why not coupled with methods like "get" and "addTo" for pitch, yaw and roll - to simplify patching the controls and coding new ones.

**Comment by m-schuetz** [comment]
> Is there a way to set the camera "up" vector with 1.5RC ?
> For the camera rotation Potree is now using pitch and yaw angles and assume the up vector is fixed.

Unfortunately, no. The up-vector is fixed to 0 / 0 / 1.

> I believe linear algebra is the way to go, why not coupled with methods like "get" and "addTo" for pitch, > yaw and roll - to simplify patching the controls and coding new ones.

In 1.5RC:

viewer.scene.view.yaw = ...
viewer.scene.view.yaw = viewer.scene.view.yaw + 0.1
viewer.scene.view.pitch = ...

> I had no success yet playing with "roll" but I dont like using trigonometry for rotations.

Roll isn't supported at the moment because yaw and pitch are usually all you need. What do you want to do with roll?

**Comment by jo-chemla** [comment]
Can be useful to set any camera orientation - useful to match the real poses of the camera that took pictures relative to an environment (like a 3D reconstruction from photogrammetry). https://doxel.org/doxel/viewer?s=58a9949d0750af3a0fce93c6

**Comment by bugdanov** [comment]
Also useful to define animation paths #281

BTW another camera could be used but then the ability to use controls during an animation (to turn the head, zoom or move relatively to the path) is gone

**Comment by bugdanov** [comment]
I can display the view I want in Potree viewer using camera.up.set() and camera.lookAt() and comment out the lines where you update camera.rotation[axis] (it's the main feature I really need immediately) but then of course the Potree controls are not working as expected anymore.

To see the running example from doxel-viewer/potree-1.5 here: http://miprosoft.org:8081/viewer.html?src=example

To go further, instead of using Euler angles directly to set "camera.rotation", I tried to convert them from and to a quaternion before accessing them (and use this quaternion to set the camera rotation matrix via camera.up.set() and camera.lookAt(), and update the Euler angles after moving the camera.)

But I messed up one or two things while trying.

See the "running" test playground for this (doxel-viewer/develop) here http://miprosoft.org:8080/viewer.html?src=example

The changes are detailed here:
https://github.com/doxel/doxel-viewer/commit/302af5c9a3ea0d53a5d56694c0ebfda5aae954b4?w=1#diff-fa554eb350c1ed79ae28467d1537cd62

Could you help me to understand what needs to be done so that the potree controls do not get confused after setting the camera up and lookAt vertices please ?

**Comment by emqiongwu** [comment]
Do  you still have the github repository for your running example: http://miprosoft.org:8081/viewer.html?src=example

I am also trying to implement a similar functionality

**Comment by emqiongwu** [comment]
Bugdanov, do you still have the source code for your running example: http://miprosoft.org:8081/viewer.html?src=example. I looked through doxel/doxel-viewer source code, and did not find your running example

I am trying to implement a similar functionality. Appreciated if you could share how did you change the potree code to make your running example. Thanks!

**Comment by tarik-djurdjevic** [comment]
> Can be useful to set any camera orientation - useful to match the real poses of the camera that took pictures relative to an environment (like a 3D reconstruction from photogrammetry). https://doxel.org/doxel/viewer?s=58a9949d0750af3a0fce93c6

Yes that is exactly what I need. Any updates regarding this?
